### ISSUE TITLE
Error getting started

### ISSUE THREAD

**Issue by mbaloch** [IBM/nl2ltl#26]
1. I have downloaded rsa model. created a directory named 'models' put the rsa model in it.
When I run the sample code provided I get the following error:
`TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

2. I choose the open-api engine and and export the api-key and try run the code, I get the following error:
```
File "C:\Users\Lenovo\.conda\envs\nl2l\lib\site-packages\openai\openai_object.py", line 59, in __getattr__
    return self[k]
KeyError: 'translate'
```
My Code

```
from nl2ltl import translate
from nl2ltl.engines.rasa.core import RasaEngine
from nl2ltl.engines.gpt.core import openai
from nl2ltl.filters.simple_filters import BasicFilter
from nl2ltl.engines.utils import pretty

# engine = RasaEngine()
engine = openai.Engine()
filter = BasicFilter()
utterance = "Eventually send me a Slack after receiving a Gmail"

ltlf_formulas = translate(utterance, engine, filter)
pretty(ltlf_formulas)

```
detailed error files are attached
[error-open-api-engine.txt](https://github.com/IBM/nl2ltl/files/12899702/error-open-api-engine.txt)
[error-rsa-engine.txt](https://github.com/IBM/nl2ltl/files/12899703/error-rsa-engine.txt)

**Comment by francescofuggitti** [comment]
Hi @mbaloch.

Could you double-check that your repository reflects the following structure?

```
/nl2ltl
    /nl2ltl
         /declare
         /engines
             /rasa
                 /models
                     nlu-.....-rasa.tar.gz
```
